version: "3.9"
services:
  mariadb:
    image: mariadb
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    restart: always
    ports:
      - "3306:3306"
    networks:
      - almak_net


  phpmyadmin:
    image: phpmyadmin
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      PMA_HOST: mariadb
      UPLOAD_LIMIT: 50M
    depends_on:
      - mariadb
    restart: always
    ports:
      - "8080:80"
    networks:
      - almak_net


  strapi:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - ./backend:/opt/app
    environment:
      NODE_ENV: ${NODE_ENV}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    depends_on:
      - mariadb
    restart: always
    ports:
      - "1337:1337"
    networks:
      - almak_net
  
networks:
  almak_net:

volumes:
  backend:
  mysql:
